# Generated by Django 6.1 on 2026-08-13 06:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASTRAEUser', '0002_usercoupon_is_for_sale_usercoupon_listed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='📦', max_length=10)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cashback', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('coupon_code', models.CharField(blank=True, default='', max_length=50)),
                ('rating', models.DecimalField(decimal_places=1, default=4.0, max_digits=3)),
                ('deal_score', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_demo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('price_drop', 'Price Drop'), ('coupon_expiring', 'Coupon Expiring'), ('coupon_sold', 'Coupon Sold'), ('coupon_purchased', 'Coupon Purchased'), ('reward_earned', 'Reward Earned'), ('order_completed', 'Order Completed'), ('new_deal', 'New Deal'), ('marketplace', 'Marketplace Activity'), ('system', 'System')], default='system', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('region', models.CharField(default='India', max_length=100)),
                ('logo_url', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', max_length=20)),
                ('integration_type', models.CharField(choices=[('mock', 'Mock'), ('api', 'API'), ('affiliate', 'Affiliate'), ('manual', 'Manual')], default='mock', max_length=20)),
                ('api_status', models.CharField(default='demo', max_length=50)),
                ('popularity_score', models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('platform', models.CharField(blank=True, default='', max_length=100)),
                ('category', models.CharField(blank=True, default='', max_length=50)),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('watching', 'Watching'), ('price_dropped', 'Price Dropped'), ('offer_available', 'Offer Available'), ('expired', 'Expired')], default='watching', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RewardRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('points', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=50)),
                ('detected_category', models.CharField(blank=True, default='', max_length=50)),
                ('result_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Search histories',
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_categories', models.JSONField(blank=True, default=list)),
                ('favorite_platforms', models.JSONField(blank=True, default=list)),
                ('max_price_preference', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notify_price_drops', models.BooleanField(default=True)),
                ('notify_coupon_expiry', models.BooleanField(default=True)),
                ('notify_deals', models.BooleanField(default=True)),
                ('notify_marketplace', models.BooleanField(default=True)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_points', models.IntegerField(default=0)),
                ('cashback_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('coupon_credits', models.IntegerField(default=0)),
                ('marketplace_earnings', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_type', models.CharField(choices=[('earned', 'Earned'), ('spent', 'Spent'), ('received', 'Received'), ('sold', 'Sold'), ('purchased', 'Purchased'), ('refunded', 'Refunded')], max_length=20)),
                ('points_delta', models.IntegerField(default=0)),
                ('cashback_delta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('reference_id', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('product', 'Product'), ('service', 'Service'), ('coupon', 'Coupon'), ('deal', 'Deal')], default='product', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('platform', models.CharField(blank=True, default='', max_length=100)),
                ('category', models.CharField(blank=True, default='', max_length=50)),
                ('current_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('previous_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lowest_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reference_id', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='astrae_savings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='cashback',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_applied',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('searching', 'Searching'), ('selected', 'Selected'), ('booking_pending', 'Booking Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='completed', max_length=20),
        ),
        migrations.AddField(
            model_name='reward',
            name='rule_key',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='reward',
            name='status',
            field=models.CharField(choices=[('earned', 'Earned'), ('pending', 'Pending'), ('redeemed', 'Redeemed')], default='earned', max_length=20),
        ),
        migrations.AddField(
            model_name='usercoupon',
            name='category',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='usercoupon',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercoupon',
            name='face_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='usercoupon',
            name='is_demo',
            field=models.BooleanField(default=True, help_text='Demo/sample coupon for development'),
        ),
        migrations.AddField(
            model_name='usercoupon',
            name='status',
            field=models.CharField(choices=[('pending_verification', 'Pending Verification'), ('verified', 'Verified'), ('listed', 'Listed'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('redeemed', 'Redeemed'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='verified', max_length=30),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='ASTRAEUser__user_id_9df650_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['category'], name='ASTRAEUser__categor_2e07aa_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['platform'], name='ASTRAEUser__platfor_9b8373_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='ASTRAEUser__status_8df37f_idx'),
        ),
        migrations.AddIndex(
            model_name='reward',
            index=models.Index(fields=['user', '-created_at'], name='ASTRAEUser__user_id_10fb3f_idx'),
        ),
        migrations.AddIndex(
            model_name='usercoupon',
            index=models.Index(fields=['user', 'is_used'], name='ASTRAEUser__user_id_a30109_idx'),
        ),
        migrations.AddIndex(
            model_name='usercoupon',
            index=models.Index(fields=['is_for_sale', 'status'], name='ASTRAEUser__is_for__e6767e_idx'),
        ),
        migrations.AddIndex(
            model_name='usercoupon',
            index=models.Index(fields=['platform'], name='ASTRAEUser__platfor_2040a9_idx'),
        ),
        migrations.AddIndex(
            model_name='usercoupon',
            index=models.Index(fields=['expiry_date'], name='ASTRAEUser__expiry__913ce4_idx'),
        ),
        migrations.AddConstraint(
            model_name='usercoupon',
            constraint=models.UniqueConstraint(fields=('coupon_code', 'platform'), name='unique_coupon_per_platform'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='platform',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='ASTRAEUser.category'),
        ),
        migrations.AddField(
            model_name='deal',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='ASTRAEUser.platform'),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='searches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='ASTRAEUser.wallet'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='ASTRAEUser__user_id_cca21b_idx'),
        ),
        migrations.AddIndex(
            model_name='platform',
            index=models.Index(fields=['category', 'status'], name='ASTRAEUser__categor_0af431_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['category', 'is_active'], name='ASTRAEUser__categor_1eebdc_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['-deal_score'], name='ASTRAEUser__deal_sc_33f375_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['expires_at'], name='ASTRAEUser__expires_e4601f_idx'),
        ),
        migrations.AddIndex(
            model_name='pricealert',
            index=models.Index(fields=['user', 'status'], name='ASTRAEUser__user_id_9fee99_idx'),
        ),
        migrations.AddIndex(
            model_name='pricealert',
            index=models.Index(fields=['target_price'], name='ASTRAEUser__target__d88e1f_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['user', '-created_at'], name='ASTRAEUser__user_id_9bcbc9_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', '-created_at'], name='ASTRAEUser__wallet__a95b73_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlistitem',
            index=models.Index(fields=['user', '-created_at'], name='ASTRAEUser__user_id_289735_idx'),
        ),
    ]
