# Generated by Django 6.1 on 2026-08-13 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASTRAEUser', '0003_category_deal_notification_platform_pricealert_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('main_benefit', models.CharField(help_text='Primary discount or benefit headline', max_length=150)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_demo', models.BooleanField(default=True, help_text='Sample event for demo/presentation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ASTRAEUser.platform')),
            ],
            options={
                'verbose_name': 'Platform event',
                'verbose_name_plural': 'Platform events',
                'indexes': [models.Index(fields=['platform_name', 'is_active'], name='ASTRAEUser__platfor_37faa3_idx'), models.Index(fields=['category'], name='ASTRAEUser__categor_7f9fe9_idx'), models.Index(fields=['starts_at'], name='ASTRAEUser__starts__fa5de2_idx'), models.Index(fields=['ends_at'], name='ASTRAEUser__ends_at_81c8c6_idx')],
            },
        ),
    ]
