# Generated by Django 6.1 on 2026-08-13 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASTRAEUser', '0005_order_booking_notes_order_delivery_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='platformevent',
            name='event_type',
            field=models.CharField(choices=[('festival', 'Festival Sale'), ('flash_sale', 'Flash Sale'), ('live_offer', 'Live Offer'), ('platform_offer', 'Platform Offer'), ('upcoming', 'Upcoming Event')], default='live_offer', max_length=30),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='alert_type',
            field=models.CharField(choices=[('price_drop', 'Price Drop'), ('coupon_expiry', 'Coupon Expiry'), ('deal_expiry', 'Deal Expiry'), ('new_offer', 'New Offer'), ('event_start', 'Event Starting')], default='price_drop', max_length=20),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='reference_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='wishlist_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='ASTRAEUser.wishlistitem'),
        ),
        migrations.AlterField(
            model_name='pricealert',
            name='status',
            field=models.CharField(choices=[('watching', 'Watching'), ('price_dropped', 'Price Dropped'), ('offer_available', 'Offer Available'), ('expired', 'Expired'), ('triggered', 'Triggered')], default='watching', max_length=20),
        ),
        migrations.AddIndex(
            model_name='pricealert',
            index=models.Index(fields=['alert_type'], name='ASTRAEUser__alert_t_fc7850_idx'),
        ),
    ]
